trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  image: 'macos-latest'

variables:
  GRADLE_USER_HOME: $(Pipeline.Workspace)/.gradle
  PROJECT_DIR: $(Build.SourcesDirectory)/BiometricApp

####################################################
# GitHub Repositories
####################################################

resources:
  repositories:
    - repository: api
      type: github
      endpoint: GithubServiceConnection
      name: unisystechhub/API

    - repository: compose
      type: github
      endpoint: GithubServiceConnection
      name: unisystechhub/Compose

####################################################
# Checkout Repositories
####################################################

steps:

- checkout: self

- checkout: api
  path: s/API

- checkout: compose
  path: s/Compose

####################################################
# Inspect Workspace
####################################################
- script: |
    echo "Pipeline.Workspace = $(Pipeline.Workspace)"
    echo "Build.SourcesDirectory = $(Build.SourcesDirectory)"
    pwd
    find $(Build.SourcesDirectory) -maxdepth 2 -type d
  displayName: "Show workspace layout"
- script: |
    echo "Build.SourcesDirectory = $(Build.SourcesDirectory)"
    pwd
    ls -la
    echo "----------------------------"
    ls -la $(PROJECT_DIR)
    echo "----------------------------"
    find $(Build.SourcesDirectory) -name gradlew
  displayName: 'Inspect Repository Structure'


####################################################
# Restore Gradle Cache
####################################################



####################################################
# Grant Execute Permission
####################################################

- script: |
    chmod +x gradlew
  workingDirectory: $(PROJECT_DIR)
  displayName: 'Grant Execute Permission'

####################################################
# Verify Java & Gradle
####################################################

- script: |
    java -version
    ./gradlew --version
  workingDirectory: $(PROJECT_DIR)
  displayName: 'Verify Java & Gradle'

####################################################
# Download Dependencies
####################################################

- script: |
    ./gradlew dependencies
  workingDirectory: $(PROJECT_DIR)
  displayName: 'Download Dependencies'

####################################################
# Verify Gradle Project
####################################################

- script: |
    ./gradlew help
  workingDirectory: $(PROJECT_DIR)
  displayName: 'Verify Gradle Project'

####################################################
# Clean
####################################################

- script: |
    ./gradlew clean
  workingDirectory: $(PROJECT_DIR)
  displayName: 'Clean Project'

####################################################
# Assemble Debug APK
####################################################

- script: |
    ./gradlew assembleDebug --stacktrace
  workingDirectory: $(PROJECT_DIR)
  displayName: 'Assemble Debug APK'

####################################################
# Unit Tests and espresso test
####################################################

- script: |
    ./gradlew testDebugUnitTest
  workingDirectory: $(PROJECT_DIR)
  displayName: 'Run Unit Tests'
- script: |
    $ANDROID_HOME/emulator/emulator \
      -avd Pixel_API_34 \
      -no-window \
      -no-audio \
      -no-boot-anim &

    $ANDROID_HOME/platform-tools/adb wait-for-device

    until $ANDROID_HOME/platform-tools/adb shell getprop sys.boot_completed | tr -d '\r' | grep -q "1"; do
      sleep 5
    done

    $ANDROID_HOME/platform-tools/adb devices
  displayName: 'Start Emulator'

- script: |
    ./gradlew connectedDebugAndroidTest
  workingDirectory: $(PROJECT_DIR)
  displayName: Run Espresso Tests
####################################################
# Android Lint
####################################################

- script: |
    ./gradlew lintDebug
  workingDirectory: $(PROJECT_DIR)
  displayName: 'Run Android Lint'

####################################################
# JaCoCo Coverage
####################################################

- script: |
    ./gradlew jacocoTestReport
  workingDirectory: $(PROJECT_DIR)
  displayName: 'Generate JaCoCo Report'

####################################################
# Publish Test Results
####################################################

- task: PublishTestResults@2
  displayName: 'Publish Unit Test Results'
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '$(PROJECT_DIR)/**/TEST-*.xml'
    mergeTestResults: true
    testRunTitle: 'Android Unit Tests'

####################################################
# Publish Code Coverage
####################################################

- task: PublishCodeCoverageResults@1
  displayName: 'Publish Code Coverage'
  condition: succeededOrFailed()
  inputs:
    codeCoverageTool: 'JaCoCo'
    summaryFileLocation: '$(PROJECT_DIR)/**/jacocoTestReport.xml'
    reportDirectory: '$(PROJECT_DIR)/**/jacocoHtml'

####################################################
# Publish APK
####################################################

- task: PublishBuildArtifacts@1
  displayName: 'Publish APK'
  condition: succeededOrFailed()
  inputs:
    PathtoPublish: '$(PROJECT_DIR)/app/build/outputs/apk/debug'
    ArtifactName: 'APK'

####################################################
# Publish Lint Report
####################################################

- task: PublishBuildArtifacts@1
  displayName: 'Publish Lint Report'
  condition: succeededOrFailed()
  inputs:
    PathtoPublish: '$(PROJECT_DIR)/app/build/reports'
    ArtifactName: 'LintReport'
